### ISSUE TITLE
Put configuration file in a volume

### ISSUE THREAD

**Issue by damajor** [linuxserver/docker-pwndrop#4]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior

Access to the configuration file.

## Current Behavior

Configuration file is embedded in the docker image.

## Alternatives Considered

None.

**Comment by aptalca** [comment]
Why?

**Comment by damajor** [comment]
Multiple reasons, for eg.:
- change listen port when network is in host mode
- setting/changing admin user and password only by editing a single file
- same idea for the redirect path

I admit that the configuration is very simple and may not require so many changes but for best practices reason it is, I think, also a good idea.

**Comment by lucawen** [comment]
yes, cant set config file from the mount data specified.
